import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const akira = localFont({
  src: "../asserts/fonts/Akira.otf",
  variable: "--font-akira",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${akira.variable} antialiased`}>{children}</body>
    </html>
  );
}
